# Generated by Django 2.2.5 on 2020-05-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('is_holiday', models.BigIntegerField()),
            ],
            options={
                'db_table': 'm_holiday_data',
            },
        ),
    ]
